name: Deploy TypingMind to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create correct directory structure
        run: |
          # Create the structure that matches our URLs
          mkdir -p deploy_root/src
          
          # Copy src contents to deploy_root/src/
          cp -r src/* deploy_root/src/
          
          # Move index.html to the root level (so it's accessible at /typingmind/)
          mv deploy_root/src/index.html deploy_root/
          
          # Fix the base tag in index.html
          sed -i 's|<head>|<head><base href="/typingmind/">|g' deploy_root/index.html
          
          # Convert absolute paths to relative paths starting with src/
          sed -i 's|href="/_next/|href="src/_next/|g' deploy_root/index.html
          sed -i 's|src="/_next/|src="src/_next/|g' deploy_root/index.html
          sed -i 's|href="/favicon|href="src/favicon|g' deploy_root/index.html
          sed -i 's|href="/manifest|href="src/manifest|g' deploy_root/index.html
          sed -i 's|href="/android-icon|href="src/android-icon|g' deploy_root/index.html
          sed -i 's|href="/apple-icon|href="src/apple-icon|g' deploy_root/index.html
          sed -i 's|href="/ms-icon|href="src/ms-icon|g' deploy_root/index.html
          sed -i 's|content="/ms-icon|content="src/ms-icon|g' deploy_root/index.html
          sed -i 's|href="/assets/|href="src/assets/|g' deploy_root/index.html
          sed -i 's|src="/assets/|src="src/assets/|g' deploy_root/index.html
          
          echo "=== DIRECTORY STRUCTURE ==="
          find deploy_root -type f | head -20
          
          echo "=== CHECKING PATHS IN HTML ==="
          grep -o 'src="[^"]*_next[^"]*"' deploy_root/index.html | head -5
          grep -o 'href="[^"]*_next[^"]*"' deploy_root/index.html | head -5
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy_root
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
