name: Deploy TypingMind to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Universal path fixing
        run: |
          cp -r src temp_build
          
          # Python script for comprehensive path fixing
          cat > fix_paths.py << 'EOF'
          import re
          
          def fix_html_paths(content):
              # Add base tag if not present
              if '<base' not in content:
                  content = content.replace('<head>', '<head><base href="/src/">')
              else:
                  # Replace existing base tag
                  content = re.sub(r'<base[^>]*>', '<base href="/src/">', content)
              
              # Convert ALL absolute paths (except external URLs) to relative paths
              # This regex matches href="/something" but not href="http://something"
              content = re.sub(r'(href|src|content)="(/(?!https?://)[^"]*)"', r'\1="\2"', content)
              
              # Remove leading slash from paths to make them relative
              content = re.sub(r'(href|src|content)="(/[^h][^"]*)"', r'\1="\2"', content)
              content = content.replace('href="/', 'href="')
              content = content.replace('src="/', 'src="')
              content = content.replace('content="/', 'content="')
              
              return content
          
          # Read and fix the HTML
          with open('temp_build/index.html', 'r', encoding='utf-8') as f:
              html_content = f.read()
          
          fixed_content = fix_html_paths(html_content)
          
          with open('temp_build/index.html', 'w', encoding='utf-8') as f:
              f.write(fixed_content)
          
          print("Fixed all paths to be relative with proper base URL")
          EOF
          
          python3 fix_paths.py
          
          echo "=== DEBUGGING: First 30 lines of fixed HTML ==="
          head -30 temp_build/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./temp_build
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
